# Generated by Django 5.1.2 on 2024-10-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_category_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.category'),
        ),
    ]
