# Generated by Django 5.1.2 on 2024-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_videomodel_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview'),
        ),
    ]
